In [2]:
!pip install numpy

  Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
# arrange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#odd numbers
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
# Reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# np.random
np.random.random((3,4))

array([[0.05481721, 0.18130773, 0.80148766, 0.54983229],
       [0.26759431, 0.60147736, 0.70915995, 0.87831541],
       [0.4551867 , 0.83411542, 0.13799025, 0.13134703]])

In [18]:
# np.linspace
"""
    Generate point in given range in equal distance
"""
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [19]:
"""
    Generate identity matrix
"""
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Attributes

In [31]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print("*"*50)
print(a2)
print("*"*50)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
**************************************************
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
**************************************************
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [23]:
# ndim --> Dimention of given array
a1.ndim

1

In [26]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [32]:
# size -> number of items
print(a1.size)
print(a2.size)

10
12


In [35]:
# itemsize -> consuption of memory by item
# output --> bite
print(a1.itemsize)
print(a2.itemsize)

8
8


In [34]:
# dtype
print(a1.dtype)

int64


#### Change datatype

In [39]:
#astype
print(a1.dtype)
a1.astype(np.int32)

int64


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### Array Operations

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [46]:
# Scalar operations

"""
    arithmetic Every arithmetic operators will work same as 
    multiplication
"""
print(a1)
a1*2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
# Relation

"""
    Every relational operators will work same as 
    greater than comparision
"""
print(a2)
a2>20

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [49]:
# Vector operations
# arithmetic

print(a1)
print("*"*50)
print(a2)
print("*"*50)

a1+a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
**************************************************


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

#### Agregation Functions

In [51]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[88. 17. 79.]
 [94. 23. 92.]
 [54.  3. 15.]]


In [52]:
# max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

94.0
3.0
465.0
57122666916480.0


In [56]:
"""
    What if you want max number from every row
    there is one parameter axis
    axis = 1 --> row
    axis = 0 --> column
"""

print(a1)
np.max(a1,axis=1)

[[88. 17. 79.]
 [94. 23. 92.]
 [54.  3. 15.]]


array([88., 94., 54.])

In [58]:
# mean/median/std/var

"""
    We can use axis parameter here also
"""
np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)

1247.5555555555557

#### Dot product

In [65]:
"""
    To get dot product of two array 
    (3,4) (4,3) ==> Possible
    (3,4) (3,4) ==> not possible
"""
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2.dot(a3)) # one way
print("*"*50)
print(np.dot(a2,a3)) # second way

[[114 120 126]
 [378 400 422]
 [642 680 718]]
**************************************************
[[114 120 126]
 [378 400 422]
 [642 680 718]]


#### Round / Floor / Ceil

In [69]:
a4 = np.random.random((2,3))*100
print(a4)
print("*"*50)
print(np.round(a4))
print("*"*50)
print(np.floor(a4))
print("*"*50)
print(np.ceil(a4))
print("*"*50)

[[22.41621018 77.92962249 68.40545289]
 [31.25082158 60.20585326  0.39878387]]
**************************************************
[[22. 78. 68.]
 [31. 60.  0.]]
**************************************************
[[22. 77. 68.]
 [31. 60.  0.]]
**************************************************
[[23. 78. 69.]
 [32. 61.  1.]]
**************************************************


#### Indexing and Slicing

In [70]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [72]:
# last item of a1
a1[-1]

9

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
# get 6
"""
    2D array ==> array[row,column]
"""
a2[1,2]

6

In [75]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
# get 5
"""
    3D array ==> array[which one array , row, column]
"""
a3[1,0,1]

5

In [78]:
# get 3,4,5
print(a1)
a1[3:6]

[0 1 2 3 4 5 6 7 8 9]


array([3, 4, 5])

In [79]:
# get 1st row in a2
print(a2)
a2[0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [81]:
# get all row and 4 column
a2[:,3]

array([ 3,  7, 11])

In [84]:
# get 6,7, 10, 11
a2[1:,2:4]

array([[ 6,  7],
       [10, 11]])

In [87]:
# get 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [90]:
# get 4,7
a2[1:2,::3]

array([[4, 7]])

In [93]:
# 1,2,3,5,6,7
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [96]:
# 3D array
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a3[0,1]

array([3, 4, 5])

In [104]:
# 2nd array 2 columns
a3[1,:,1]

array([10, 13, 16])

In [109]:
# get 22,23,25,26
a3[2,1:3,1:]

array([[22, 23],
       [25, 26]])

In [114]:
# get 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

#### Reshaping

In [117]:
# Transpose
print(a2)
a2.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [119]:
# ravel ---> flat array 
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [120]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Splitting

In [122]:
# Horizontal splitting
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [126]:
a6 = np.hstack((a4,a5))

In [127]:
a7 = np.vstack((a4,a5))

In [128]:
a6

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [129]:
a7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [134]:
np.hsplit(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [135]:
np.vsplit(a7,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]